### PR TITLE
fixes duplicate tags in docs

### PR DESCRIPTION
**Pull request by IllustratedMan-code**
I just changed the names of the duplicate tags.

### CODE REVIEW

**Comment by smjonas** [comment]
Thanks for the PR! Unfortunately I can't merge this in its current state because the docs are auto-generated from the [documentation.md](https://github.com/smjonas/snippet-converter.nvim/blob/main/doc/documentation.md) file using https://github.com/kdheepak/panvimdoc. And I also don't want to rename the `## Examples` sections in documentation.md. I have created an issue on the panvimdoc repo: https://github.com/kdheepak/panvimdoc/issues/18

**Comment by IllustratedMan-code** [comment]
I understand, seemed like an easy fix so I gave it a go. I'll close.

**Comment by IllustratedMan-code** [comment]
@smjonas it looks like the author of panvimdoc added a workaround!

**Comment by smjonas** [comment]
Yup, it should be fixed after merging the next PR

**Pull request closed without merging**
